"""Harbor — a local web dashboard for managing multiple git repositories."""

try:
    from ._version import __version__  # generated by setuptools-scm at build time
except ImportError:
    # Running from a source checkout without a build step — provide a
    # default so `import harbor` still works (tests, `python -m harbor`, ...).
    __version__ = "0.1.0-dev"
